# Setup
title:               San Kang's blog
tagline:             
description:         Welcome to my blog!
url:                 https://blog.rivmt.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              San Kang
  url:               https://github.com/RivMt
  email:             devrivmt@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
